name: Build + Test + Publish
on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - '**.rb'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Run tests
      run: |
        echo '======================================='
        echo '          Running Unit Tests           '
        echo '======================================='
        gem install bundle
        bundle install
        bundle exec rake test

    - name: Publish to GPR
      run: |
        echo '======================================='
        echo 'Publishing to GitHub Package Repository'
        echo '======================================='
        # mkdir -p $HOME/.gem
        # touch $HOME/.gem/credentials
        # chmod 0600 $HOME/.gem/credentials
        # printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        # gem install bundle
        # bundle install
        # gem build *.gemspec
        # gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        echo '======================================='
        echo '  Publishing to Ruby Gems Repository   '
        echo '======================================='
        # mkdir -p $HOME/.gem
        # touch $HOME/.gem/credentials
        # chmod 0600 $HOME/.gem/credentials
        # printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        # gem install bundle
        # bundle install
        # gem build *.gemspec
        # gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_APIKEY}}"
